---
version: "3.9"

x-podman:
  &podman
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-logging:
  &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m

volumes:
  ovos_tts_piper_cache:
    name: ovos_tts_piper_cache
    driver: local
  ovos_tts_piper_gradio_cache:
    name: ovos_tts_piper_gradio_cache
    driver: local
  ovos_tts_mimic3_cache:
    name: ovos_tts_mimic3_cache
    driver: local
  ovos_tts_mimic3_gradio_cache:
    name: ovos_tts_mimic3_gradio_cache
    driver: local
  ovos_tts_mimic_cache:
    name: ovos_tts_mimic_cache
    driver: local
  ovos_tts_mimic_gradio_cache:
    name: ovos_tts_mimic_gradio_cache
    driver: local
  ovos_tts_sam_cache:
    name: ovos_tts_sam_cache
    driver: local
  ovos_tts_sam_gradio_cache:
    name: ovos_tts_sam_gradio_cache
    driver: local
  ovos_tts_google_tx_cache:
    name: ovos_tts_google_tx_cache
    driver: local
  ovos_tts_google_tx_gradio_cache:
    name: ovos_tts_google_tx_gradio_cache
    driver: local
  ovos_tts_matxa_cache:
    name: ovos_tts_matxa_cache
    driver: local
  ovos_tts_matxa_gradio_cache:
    name: ovos_tts_matxa_gradio_cache
    driver: local
  ovos_tts_nos_cache:
    name: ovos_tts_nos_cache
    driver: local
  ovos_tts_nos_gradio_cache:
    name: ovos_tts_nos_gradio_cache
    driver: local
  ovos_tts_kokoro_cache:
    name: ovos_tts_kokoro_cache
    driver: local
  ovos_tts_kokoro_gradio_cache:
    name: ovos_tts_kokoro_gradio_cache
    driver: local

services:
  ovos_tts_piper:
    <<: *podman
    container_name: ovos_tts_piper
    hostname: ovos_tts_piper
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-piper:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8089:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      - ovos_tts_piper_cache:/home/${OVOS_USER}/.local/share/piper_tts
      - ovos_tts_piper_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_tts_mimic3:
    <<: *podman
    container_name: ovos_tts_mimic3
    hostname: ovos_tts_mimic3
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-mimic3:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8090:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      - ovos_tts_mimic3_cache:/home/${OVOS_USER}/.local/share/mycroft/mimic3
      - ovos_tts_mimic3_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_tts_mimic:
    <<: *podman
    container_name: ovos_tts_mimic
    hostname: ovos_tts_mimic
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-mimic:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8091:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      - ovos_tts_mimic_cache:/home/${OVOS_USER}/.cache/mycroft/MimicTTSPlugin
      - ovos_tts_mimic_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_tts_google_tx:
    <<: *podman
    container_name: ovos_tts_google_tx
    hostname: ovos_tts_google_tx
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-google-tx:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8092:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      - ovos_tts_google_tx_cache:/home/${OVOS_USER}/.cache/mycroft/GoogleTranslateTTS
      - ovos_tts_google_tx_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_tts_sam:
    <<: *podman
    container_name: ovos_tts_sam
    hostname: ovos_tts_sam
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-sam:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8094:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      - ovos_tts_sam_cache:/home/${OVOS_USER}/.cache/mycroft/SAMTTS
      - ovos_tts_sam_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_tts_matxa:
    <<: *podman
    container_name: ovos_tts_matxa
    hostname: ovos_tts_matxa
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-matxa:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8095:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      - ovos_tts_matxa_cache:/home/${OVOS_USER}/.local/share/OpenVoiceOS
      - ovos_tts_matxa_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_tts_nos:
    <<: *podman
    container_name: ovos_tts_nos
    hostname: ovos_tts_nos
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-nos:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8096:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      - ovos_tts_nos_cache:/home/${OVOS_USER}/.local/share/nos_tts_models
      - ovos_tts_nos_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_tts_kokoro:
    <<: *podman
    container_name: ovos_tts_kokoro
    hostname: ovos_tts_kokoro
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-kokoro:${VERSION}
    build:
      context: .
      dockerfile: kokoro/Dockerfile
      args:
        VERSION: ${VERSION}
    logging: *default-logging
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8097:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      - ovos_tts_kokoro_cache:/home/${OVOS_USER}/.cache
      - ovos_tts_kokoro_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_tts_coqui:
    <<: *podman
    container_name: ovos_tts_coqui
    hostname: ovos_tts_coqui
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-coqui:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    entrypoint: ovos-tts-server --engine coqui
    environment:
      TZ: $TZ
    ports:
      - "8093:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      # - ovos_tts_google_tx_cache:/home/${OVOS_USER}/.cache/mycroft/GoogleTranslateTTS
      # - ovos_tts_google_tx_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_tts_bark:
    <<: *podman
    container_name: ovos_tts_bark
    hostname: ovos_tts_bark
    restart: unless-stopped
    image: docker.io/smartgic/ovos-tts-server-bark:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    environment:
      TZ: $TZ
      CT2_CUDA_ALLOW_FP16: 1
      SUNO_USE_SMALL_MODELS: "True"
      SUNO_OFFLOAD_CPU: "True"
    ports:
      - "8094:9666"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro,z
      # - ovos_tts_google_tx_cache:/home/${OVOS_USER}/.cache/mycroft/GoogleTranslateTTS
      # - ovos_tts_google_tx_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples
